### ISSUE TITLE
iOS模拟器无法运行

### ISSUE THREAD

**Issue by DrMatioDevelop** [snice/easy-weex#1]
clone下项目来后  **npm install**    然后  **weex run ios**; 出现如下问题
`17:19:55 : Move JSbundle to dist
17:19:55 : Could not find Xcode project files in ios folder.
17:19:55 : Please make sure you have installed iOS Develop Environment and CocoaPods
`
可以运行其他的weex demo到模拟器。新手求教 🙂

**Comment by snice** [comment]
由于weex-toolkit 使用比较麻烦，我这个是不需要使用weex-toolkit 既可编译。因此weex run ios 是不支持的。我会备注上这些的，谢谢！
